### ISSUE TITLE
Citrix Workspace App: Abschnitt "Konfiguration" mittlerweile anders?

### ISSUE THREAD

**Issue by mendel5** [return42/handsOn#1]
Hallo, danke für die Anleitung zum Einrichten der Citrix Workspace App unter Linux. Ich verwende die Version `Citrix Workspace app 2101 for Linux`. Mir sind zwei Dinge aufgefallen, als ich die Einrichtung bei mir durchgeführt habe.

### 1. Pfad stimmt nicht
Laut dem Abschnitt [https://return42.github.io/handsOn/citrix/index.html#konfiguration](https://return42.github.io/handsOn/citrix/index.html#konfiguration) verlinkt die Datei `/opt/Citrix/ICAClient/config/wfclient.template` auf eine Konfig-Datei in einem Ordner der jeweiligen Landessprache. Mein System ist auf Englisch eingestellt, weshalb es bei mir `/en/` statt `/de/` ist.

Als Beispiel wird die Datei `/opt/Citrix/ICAClient/<lang>/nls/de/wfclient.template` genannt. Bei mir lautet der Pfad aber `/opt/Citrix/ICAClient/nls/en/wfclient.template`. Das `<lang>` und das `/de/` sind in der aktuellen Dokumentation aus meiner Sicht doppelt. Stattdessen sollte es lauten `/opt/Citrix/ICAClient/nls/<lang>/wfclient.template`.

### 2. Wert in der Konfig-Datei stimmt nicht
Dann wird die Anpassung der Konfig-Datei beschrieben, die in der aktuellen Version so lautet:
```
[WFClient]
...
CDMAllowed=Off
; CDMReadOnly=On
CREnabled=Off
CientPrinterQueue=Off
ClientManagement=Off
ClientComm=Off
```
Bei mir sieht der Abschnitt so aus:
```
[WFClient]
...
CREnabled=True
CDMAllowed=On
ClientPrinterQueue=On
ClientManagement=On
ClientComm=On
```
Die Werte, wo bei mir `On` steht, habe ich auf `Off` gesetzt. Nur den Wert `CREnabled=True` habe ich auf `CREnabled=False` gesetzt. Der Wert `CREnabled=Off` in der aktuellen Version der Doku müsste nach meiner Einschätzung von `Off` statt `False` gesetzt werden.

**Comment by return42** [comment]
@mendel5 vielen Dank für Deine Hinweise / ich hab sie eingearbeitet / OT: nicht erschrecken, ich hab das Layout auf meine neuen Vorlagen umgestellt.

**Comment by mendel5** [comment]
@return42 Vielen Dank für deine schnelle Rückmeldung und Einarbeitung!
